### ISSUE TITLE
Distributed files requirements

### ISSUE THREAD

**Issue by Andarist** [adobe-private/react-spectrum-v3#664]
# ❔ Question

From what I understand you still support IE11 at Adobe. The distributed files are using ES6 syntax though, so my question is - is the expectation that consumers should transpile them on their own? It's not a popular choice I would say (not necessarily a bad one though) so I thought I'd ask. If this is the expectation then I think it would be good to include a warning about this - ignoring `node_modules` from transpilation jobs is pretty common.

**Comment by devongovett** [comment]
We don't support IE11 anymore actually. The browserslist is here https://github.com/adobe-private/react-spectrum-v3/blob/8b4f315006167b1f1f34f37964e037b147384147/package.json#L10-L15

I believe all of those browsers support ES modules natively: https://caniuse.com/#feat=es6-module

We offer the CommonJS version for use in node (e.g. tests), but I don't think we need to transpile down further since node also supports all of the other ES6 syntax we use.

**Comment by Andarist** [comment]
Ok, I was under the impression that you support IE11 as it was mentioned here: https://github.com/adobe-private/react-spectrum-v3/blob/f0f104dbd5e2e70b954e50308f64ec8b2e61ab7e/rfcs/2019-v3-theming.md#native-css-variables

**Comment by devongovett** [comment]
Ah yeah those RFCs are pretty old. Since then, it was dropped.

**Comment by Andarist** [comment]
Fair enough, thanks for the clarification!
